SELECT * FROM VG69999.DOC_TYPE WHERE  DOC_TYPE_ID=613        --DOC_TYPE_DESC = 'ABANDONMENT OF ASSUMED NAME'  --613

SELECT * FROM VG69999.ORDER_ITEM_TYPE_DOC_TYPE WHERE DOC_TYPE_ID_DOC = 613



SELECT * FROM VG69999.DOC_TYPE  WHERE doc_type_desc = 'ABANDONMENT'

SELECT * FROM VG69999.SEARCH_DOC_TYPE WHERE DOC_TYPE_ID = 613

SELECT * FROM VG69999.ERDOCTYPE_DOCTYPE 
WHERE  ERDOCTYPE_DOCTYPE_ID IN (87,88,89,90)        --DOC_TYPE_DESC = 'ABANDONMENT OF ASSUMED NAME'
ORDER BY ERDOCTYPE_DESC ASC --87,88,89,90

SELECT * FROM VG69999.DOCGROUP_DOCTYPE WHERE DOC_TYPE_ID = 613 --613-1



select
  dg.doc_group_desc,
  dt.doc_type_desc
from VG69999.doc_master dm
join VG69999.order_item oi on dm.dm_id = oi.dm_id
join VG69999.doc_group dg on oi.doc_group_id = dg.doc_group_id
join VG69999.doc_type dt on dm.doc_type_id = dt.doc_type_id
where dm.dm_id in
(
select DM_ID from VG69999.ORDER_ITEM
where order_id in (
select order_id from VG69999.[ORDER]
where order_num='20230526000019'
) )

------------Select eRecording doc types per Department--------------

SELECT 
        erdt.ERDOCTYPE_DESC AS 'eRecording Doc Type',
		erdt.DOC_TYPE_DESC
FROM vg69999.ERDOCTYPE_DOCTYPE erdt 
JOIN VG69999.DOC_TYPE dt ON erdt.DOC_TYPE_DESC = dt.DOC_TYPE_DESC 
JOIN VG69999.DOCGROUP_DOCTYPE dg_dt ON dt.DOC_TYPE_ID = dg_dt.DOC_TYPE_ID 
JOIN VG69999.DEPT_DOCGROUP d_dg ON dg_dt.DOC_GROUP_ID = d_dg.DOC_GROUP_ID WHERE d_dg.DEPT_ID = 1 
ORDER BY erdt.ERDOCTYPE_DESC

SELECT * FROM VG69999.doc_type WHERE doc_type_desc = 'WITHDRAWAL OF ASSUMED NAME'
SELECT * FROM VG69999.DOCGROUP_DOCTYPE WHERE doc_type_id = 592
SELECT * FROM VG69999.doc_group	
----------------------------------------

SELECT 
   
  dt.DOC_TYPE_DESC,
  dt.IS_ACTIVE,
  oit.ORDER_ITEM_TYPE_DISPLAY_NAME,
  oitdt.IS_ACTIVE,
  oitdt.IS_DEFAULT
FROM VG69999.ORDER_ITEM_TYPE_DOC_TYPE oitdt
join VG69999.doc_type dt on oitdt.DOC_TYPE_ID_DOC = dt.doc_type_id
JOIN VG69999.ORDER_ITEM_TYPE oit ON oit.ORDER_ITEM_TYPE_ID = oitdt.ORDER_ITEM_TYPE_ID
WHERE --dt.DOC_TYPE_DESC = 'ABANDONMENT OF ASSUMED NAME'
      oit.ORDER_ITEM_TYPE_ID = 1
	  AND oitdt.IS_DEFAULT = 1
ORDER BY oit.ORDER_ITEM_TYPE_DISPLAY_NAME ASC


-----------------------------

SELECT 
        oit.ORDER_ITEM_TYPE_ID, 
		oit.ORDER_ITEM_TYPE_DISPLAY_NAME AS 'Document Type Available at Order Entry ', 
		oit_dt.IS_ACTIVE, 
		oit_dt.IS_DEFAULT,
		st.SERVICE_TYPE_DESC
FROM VG69999.DOCGROUP_DOCTYPE dg_dt
JOIN VG69999.DOC_TYPE dt ON dg_dt.DOC_TYPE_ID = dt.DOC_TYPE_ID
JOIN VG69999.DOC_GROUP dg ON dg_dt.DOC_GROUP_ID = dg.DOC_GROUP_ID
JOIN VG69999.WORKFLOW wf ON dg.DOC_GROUP_ID = wf.DOC_GROUP_ID
JOIN VG69999.ORDER_ITEM_TYPE oit ON wf.ORDER_ITEM_TYPE_ID = oit.ORDER_ITEM_TYPE_ID
JOIN VG69999.TENANT_SERVICE_TYPE tst ON wf.TENANT_SERVICE_TYPE_ID = tst.TENANT_SERVICE_TYPE_ID
JOIN VANGUARD.SERVICE_TYPE st ON tst.SERVICE_TYPE_ID = st.SERVICE_TYPE_ID
JOIN VG69999.TENANT_ORIGIN t_o ON wf.TENANT_ORIGIN_ID = t_o.TENANT_ORIGIN_ID
JOIN VANGUARD.ORIGIN o ON t_o.ORIGIN_ID = o.ORIGIN_ID
LEFT JOIN VG69999.ORDER_ITEM_TYPE_DOC_TYPE oit_dt ON oit.ORDER_ITEM_TYPE_ID = oit_dt.ORDER_ITEM_TYPE_ID AND dt.DOC_TYPE_ID = oit_dt.DOC_TYPE_ID_DOC
WHERE st.SERVICE_TYPE_DESC IN ('Recording', 'eFile', 'Indexing', 'Capture', 'Marriage', 'Filings')
AND o.ORIGIN_ID NOT IN (5, 20)
AND dt.DOC_TYPE_DESC = 'ABANDONMENT OF ASSUMED NAME' --AND oit.ORDER_ITEM_TYPE_ID IN (1, 240)
ORDER BY oit.ORDER_ITEM_TYPE_DISPLAY_NAME 


--SELECT * FROM VG69999.ORDER_ITEM_TYPE WHERE ORDER_ITEM_TYPE_ID = 240
--SELECT * FROM VG69999.WORKFLOW WHERE ORDER_ITEM_TYPE_ID = 240
--SELECT * FROM VG69999.TENANT_SERVICE_TYPE WHERE TENANT_SERVICE_TYPE_ID = 77
--SELECT * FROM VANGUARD.SERVICE_TYPE WHERE SERVICE_TYPE_ID = 2





SELECT 
        dt.DOC_TYPE_ID,
		dt.DOC_TYPE_DESC
FROM VG69999.ORDER_ITEM_TYPE_DOC_TYPE oitdt
JOIN VG69999.DOC_TYPE dt ON dt.DOC_TYPE_ID = oitdt.DOC_TYPE_ID_DOC
WHERE order_item_type_id = 1


