SELECT af.ADDITIONAL_FEE_NAME,
       oitaf.ADDITIONAL_FEE_TYPE_ID,
	   aft.ADDITIONAL_FEE_TYPE_NAME
FROM VG69999.ORDER_ITEM_TYPE_ADDITIONAL_FEE oitaf
join VG69999.ADDITIONAL_FEE af on oitaf.ADDITIONAL_FEE_ID = af.ADDITIONAL_FEE_ID
join VANGUARD.ADDITIONAL_FEE_TYPE aft on oitaf.ADDITIONAL_FEE_TYPE_ID = aft.ADDITIONAL_FEE_TYPE_ID
where ORDER_ITEM_TYPE_ID = 282
--and oitaf.ADDITIONAL_FEE_TYPE_ID is not NULL

select * from VG69999.ADDITIONAL_FEE
--where ADDITIONAL_FEE_ID in (8,9,10,11)

SELECT * FROM VANGUARD.ADDITIONAL_FEE_TYPE

select * from VG69999.ORDER_ITEM_TYPE_ADDITIONAL_FEE where ORDER_ITEM_TYPE_ID = 282
--update VG69999.ORDER_ITEM_TYPE_ADDITIONAL_FEE set ADDITIONAL_FEE_TYPE_ID = 5 where ORDER_ITEM_TYPE_ADDITIONAL_FEE_ID = 62


--------------------------------------

SELECT * FROM VG69999.ORDER_ITEM_TYPE_TEMPLATE WHERE ORDER_ITEM_TYPE_ID = 282
SELECT * FROM VG69999.TEMPLATES WHERE TEMPLATE_ID IN (65, 66)
update VG69999.ORDER_ITEM_TYPE_TEMPLATE set TEMPLATE_ID = 66 
where ORDER_ITEM_TYPE_ID = 282 and TEMPLATE_ID = 65

------------

