
SELECT ADDITIONAL_FEE_PARAMETER.* FROM vg51013.ADDITIONAL_FEE
JOIN vg51013.ADDITIONAL_FEE_ADDITIONAL_FEE_PARAMETER ON ADDITIONAL_FEE_ADDITIONAL_FEE_PARAMETER.ADDITIONAL_FEE_ID = ADDITIONAL_FEE.ADDITIONAL_FEE_ID
JOIN vg51013.ADDITIONAL_FEE_PARAMETER ON ADDITIONAL_FEE_PARAMETER.ADDITIONAL_FEE_PARAMETER_ID = ADDITIONAL_FEE_ADDITIONAL_FEE_PARAMETER.ADDITIONAL_FEE_PARAMETER_ID
WHERE ADDITIONAL_FEE_NAME = 'City Grantor Tax (Consideration)'

SELECT ADDITIONAL_FEE_PARAMETER.* FROM vg51013.ADDITIONAL_FEE
JOIN vg51013.ADDITIONAL_FEE_ADDITIONAL_FEE_PARAMETER ON ADDITIONAL_FEE_ADDITIONAL_FEE_PARAMETER.ADDITIONAL_FEE_ID = ADDITIONAL_FEE.ADDITIONAL_FEE_ID
JOIN vg51013.ADDITIONAL_FEE_PARAMETER ON ADDITIONAL_FEE_PARAMETER.ADDITIONAL_FEE_PARAMETER_ID = ADDITIONAL_FEE_ADDITIONAL_FEE_PARAMETER.ADDITIONAL_FEE_PARAMETER_ID
WHERE ADDITIONAL_FEE_NAME = 'Deed'

---------------------------------------------------------


select * from VG51013.doc_type_taxable_form 
select * from VG51013.tax_exempt_code
select * from VG51013.tax_exempt_amntrange
select * from VG51013.tax_amntrange
select * from VG51013.tax_amntrange_details

SELECT * FROM vg51013.TAX_EXEMPT_ADD_FEE
insert into  vg51013.TAX_EXEMPT_ADD_FEE values (1, 161)
SELECT * FROM vg51013.ADDITIONAL_FEE where additional_fee_name ='(213) Grantee Tax Local ARL' --161


-------------------

SELECT dt.DOC_TYPE_DESC, af.ADDITIONAL_FEE_NAME,  * FROM vg51013.DOC_TYPE_ADDITIONAL_FEE dtaf JOIN vg51013.DOC_TYPE dt 
ON dtaf.DOC_TYPE_ID = dt.DOC_TYPE_ID JOIN vg51013.ADDITIONAL_FEE af  ON dtaf.ADDITIONAL_FEE_ID = af.ADDITIONAL_FEE_ID WHERE
dtaf.ADDITIONAL_FEE_ID in (SELECT  afap.ADDITIONAL_FEE_ID FROM vg51013.ADDITIONAL_FEE af JOIN vg51013.ADDITIONAL_FEE_ADDITIONAL_FEE_PARAMETER afap ON
af.ADDITIONAL_FEE_ID = afap.ADDITIONAL_FEE_ID JOIN vg51013.ADDITIONAL_FEE_PARAMETER afp ON afp.ADDITIONAL_FEE_PARAMETER_ID = afap.ADDITIONAL_FEE_PARAMETER_ID  
WHERE afp.ADDITIONAL_FEE_PARAMETER_NAME = 'IsTaxRateIncluded')

-------------------

SELECT * FROM vg51013.ADDITIONAL_FEE_ADDITIONAL_FEE_PARAMETER WHERE ADDITIONAL_FEE_PARAMETER_ID = 28
SELECT * FROM vg51013.ADDITIONAL_FEE WHERE ADDITIONAL_FEE_ID IN (
SELECT ADDITIONAL_FEE_ID FROM vg51013.ADDITIONAL_FEE_ADDITIONAL_FEE_PARAMETER WHERE ADDITIONAL_FEE_PARAMETER_ID = 27)

SELECT * FROM vg51013.DOC_TYPE WHERE DOC_TYPE_ID IN (
SELECT DOC_TYPE_ID FROM vg51013.DOC_TYPE_ADDITIONAL_FEE WHERE ADDITIONAL_FEE_ID IN (
SELECT ADDITIONAL_FEE_ID FROM vg51013.ADDITIONAL_FEE_ADDITIONAL_FEE_PARAMETER WHERE ADDITIONAL_FEE_PARAMETER_ID = 27))


SELECT * FROM vg51013.ADDITIONAL_FEE_PARAMETER WHERE ADDITIONAL_FEE_PARAMETER_ID IN (
SELECT ADDITIONAL_FEE_PARAMETER_ID FROM vg51013.ADDITIONAL_FEE_ADDITIONAL_FEE_PARAMETER WHERE ADDITIONAL_FEE_ID = 161)

SELECT * FROM vg51013.DOC_TYPE_TAXABLE_FORM
SELECT * FROM vg51013.TAX_AMNTRANGE_DETAILS


SELECT * FROM vg51013.ADDITIONAL_FEE_PARAMETER
SELECT * FROM vg51013.APPRAISAL

SELECT * FROM vg51013.DOC_TYPE_ADDITIONAL_FEE WHERE ADDITIONAL_FEE_ID IN (120,129,165)


--INSERT INTO vg51013.TAX_EXEMPT_ADD_FEE
(
    TAX_EXEMPT_CODE_ID,
    ADD_FEE_ID
)
VALUES
(   1, -- TAX_EXEMPT_CODE_ID - int
    160  -- ADD_FEE_ID - int
    )

    SELECT * FROM vg51013.ADDITIONAL_FEE_PARAMETER


	select  
	      af.additional_fee_name,
		  afp.additional_fee_parameter_name,
		  afp.additional_fee_parameter_value
	FROM vg51013.DOC_TYPE_ADDITIONAL_FEE dtaf
	JOIN vg51013.ADDITIONAL_FEE af  ON dtaf.ADDITIONAL_FEE_ID = af.ADDITIONAL_FEE_ID
	JOIN vg51013.ADDITIONAL_FEE_ADDITIONAL_FEE_PARAMETER afap ON af.ADDITIONAL_FEE_ID = afap.ADDITIONAL_FEE_ID
	JOIN vg51013.ADDITIONAL_FEE_PARAMETER afp ON afp.ADDITIONAL_FEE_PARAMETER_ID = afap.ADDITIONAL_FEE_PARAMETER_ID 
	where doc_type_id = 37 and 
	      af.ADDITIONAL_FEE_NAME like '%Grantee%' and
		  afp.ADDITIONAL_FEE_PARAMETER_NAME = 'Increment'


select * from VG51013.appraisal where is_city_parcel = 1
update VG51013.appraisal set is_city_parcel = 1 where parcel_id = '01001001'

-----


----------------------


select * from VG48999.CRS_SECURITY_AD_USERGROUP where crs_security_ad_usergroup_securable_pk = 40530
select * from VG48999.WORKFLOW_ACTION where action = 'User#Users'

SELECT * FROM VG48999.CRS_SECURITY_AD_USERGROUP
WHERE
        
(
	(CRS_SECURABLE_ID = (SELECT CRS_SECURABLE_ID FROM VANGUARD.CRS_SECURABLE
	WHERE CRS_SECURABLE_OBJECT = 'WORKFLOW_ACTION')
	AND
	CRS_SECURITY_AD_USERGROUP_SECURABLE_PK = (SELECT
	ACTION_ID FROM VG48999.WORKFLOW_ACTION WHERE [ACTION] = 'User#Users') )
	OR
	(CRS_SECURABLE_ID = (SELECT CRS_SECURABLE_ID FROM VANGUARD.CRS_SECURABLE
	WHERE CRS_SECURABLE_OBJECT = 'WORKFLOW_ACTION') AND CRS_SECURITY_AD_USERGROUP_ALLOW_ALL = 1)
)

-----------------

select * from VG69999.CRS_SECURITY_AD_USERGROUP where crs_security_ad_usergroup_securable_pk = 40530
select * from VG69999.WORKFLOW_ACTION where action = 'User#Users'

SELECT * FROM VG69999.CRS_SECURITY_AD_USERGROUP
WHERE
        
(
	(CRS_SECURABLE_ID = (SELECT CRS_SECURABLE_ID FROM VANGUARD.CRS_SECURABLE
	WHERE CRS_SECURABLE_OBJECT = 'WORKFLOW_ACTION')
	AND
	CRS_SECURITY_AD_USERGROUP_SECURABLE_PK = (SELECT
	ACTION_ID FROM VG69999.WORKFLOW_ACTION WHERE [ACTION] = 'User#Users') )
	OR
	(CRS_SECURABLE_ID = (SELECT CRS_SECURABLE_ID FROM VANGUARD.CRS_SECURABLE
	WHERE CRS_SECURABLE_OBJECT = 'WORKFLOW_ACTION') AND CRS_SECURITY_AD_USERGROUP_ALLOW_ALL = 1)
)

select * from VG48999.appraisal where legal_desc like '%;%'
--LOTS 22A & NORTH; 1/3 OF LOT 24-A, BLOCK  L; SHERWOOD;
select * from VG69999.appraisal
--update VG69999.appraisal set legal_desc = 'LOTS 22A & NORTH; 1/3 OF LOT 24-A, BLOCK  L; SHERWOOD' where parcel_id = '12-345-679'
--parcel_id = '12-345-679'
--LEGAL; DESCRIPTION



select * from Vg51013.intranet_device
--select * from Vg69999.intranet_device where device_desc like '%Artyom%'

INSERT INTO [VANGUARD_TX_QA].[VG51013].[INTRANET_DEVICE]
         ( [DEVICE_HOST_NAME] , [DEVICE_HOST_ADDR] , [DEVICE_DESC] , [ISACTIVE] ,[DEVICETYPE_ID])
 VALUES  ( '10.11.252.23' , '10.11.252.23' , 'Artyom Kiosk',  1, 1)


-----------------------

select * from VG51013.appraisal where is_city_parcel = 1

--select * from VG51013.appraisal where parcel_id = '51121008'

select * from VG51013.erdoctype_doctype where doc_type_desc = 'ELECTRONIC B&S'




