

-- user groups 2, 6, 7 and 8 should have access for the NoFee. 
-- User groups 1 through 8 should have access to CaptureUploadImageReplace.
select * from VG48999.AD_USERGROUP

------------------


select * from VANGUARD.CRS_SECURABLE
select * from VG69999.WORKFLOW_ACTION where ACTION like 'Order#Finalize%'
select * from VG69999.WORKFLOW_ACTION where ACTION_ID = 40515
select * from VANGUARD.SERVICE_TYPE

-----------------------------------------------------------
SELECT * FROM VG69999.CRS_SECURITY_AD_USERGROUP
WHERE
        --AU_UG_ID = 1 -- This would be the AD_USERGROUP_ID
        --AND
(
	(CRS_SECURABLE_ID = (SELECT CRS_SECURABLE_ID FROM VANGUARD.CRS_SECURABLE
	WHERE CRS_SECURABLE_OBJECT = 'WORFKLOW_ACTION')
	AND
	CRS_SECURITY_AD_USERGROUP_SECURABLE_PK = (SELECT
	ACTION_ID FROM VG69999.WORKFLOW_ACTION WHERE [ACTION] = 'Order#FinalizeVoidOrder') )
	OR
	(CRS_SECURABLE_ID = (SELECT CRS_SECURABLE_ID FROM VANGUARD.CRS_SECURABLE
	WHERE CRS_SECURABLE_OBJECT = 'WORKFLOW_ACTION') AND CRS_SECURITY_AD_USERGROUP_ALLOW_ALL = 1)
)
------------------------------------------------------------------------------

SELECT * FROM VG48999.CRS_SECURITY_AD_USERGROUP
WHERE
--AU_UG_ID = 1 -- This would be the AD_USERGROUP_ID
--AND
(
	(CRS_SECURABLE_ID = (SELECT CRS_SECURABLE_ID FROM VANGUARD.CRS_SECURABLE
	WHERE CRS_SECURABLE_OBJECT = 'SERVICE_TYPE')
	AND
	CRS_SECURITY_AD_USERGROUP_SECURABLE_PK = (SELECT
	SERVICE_TYPE_ID FROM VANGUARD.SERVICE_TYPE WHERE SERVICE_TYPE_DESC = 'Re-Capture') )
	OR
	(CRS_SECURABLE_ID = (SELECT CRS_SECURABLE_ID FROM VANGUARD.CRS_SECURABLE
	WHERE CRS_SECURABLE_OBJECT = 'SERVICE_TYPE') AND CRS_SECURITY_AD_USERGROUP_ALLOW_ALL = 1)
)    
order by au_ug_id asc
---------------------------------------------------------------------------------------------------------

SELECT * FROM VG48999.CRS_SECURITY_AD_USERGROUP
WHERE
(
    (CRS_SECURABLE_ID = (SELECT CRS_SECURABLE_ID FROM VANGUARD.CRS_SECURABLE
    WHERE CRS_SECURABLE_OBJECT = 'WORFKLOW_ACTION')
    AND
    CRS_SECURITY_AD_USERGROUP_SECURABLE_PK = (SELECT
    ACTION_ID FROM VG48999.WORKFLOW_ACTION WHERE [ACTION] = 'Capture#ReplaceArchivedImage') )  
    OR
    (CRS_SECURABLE_ID = (SELECT CRS_SECURABLE_ID FROM VANGUARD.CRS_SECURABLE
    WHERE CRS_SECURABLE_OBJECT = 'WORKFLOW_ACTION') AND CRS_SECURITY_AD_USERGROUP_ALLOW_ALL = 1)
)  




