DECLARE @Info table
	(
		[ADUSER_DOMAIN] nvarchar(255),
		[DEVICE_NAME] nvarchar(255),
		[ADUSER_FIRSTNAME] nvarchar(255),
		[ADUSER_LASTNAME] nvarchar(255),
		[ADUSER_EMAILID] nvarchar(255),
		[WORK_STATION_NAME] nvarchar(128),
		[WORK_STATION_ADDRESS] nvarchar(128)
	)

DECLARE @WorkStationName nvarchar(50)
Set @WorkStationName = N'10.0.2.247'


insert @info ([aduser_domain],[device_name],[aduser_firstname], [aduser_lastname], [aduser_emailid], [work_station_name], [work_station_address])
values (N'volo-dc\artyom.shchokin', N'volo-dc\artyom.shchokin', N'artyom',N'shchokin', N'artyom.shchokin@volo.global', @WorkStationName, @WorkStationName)


print 'Delete existing users'

DELETE FROM vg48273.AD_USER_LOGIN_STATISTIC WHERE ADUSER_ID IN (SELECT ADUSER_ID FROM vg48273.AD_USER WHERE ADUSER_DOMAIN IN (SELECT [ADUSER_DOMAIN] FROM @Info))
DELETE FROM vg48273.CRS_LOCKED_ELEMENT WHERE ADUSER_ID IN (SELECT ADUSER_ID FROM vg48273.AD_USER WHERE ADUSER_DOMAIN IN (SELECT [ADUSER_DOMAIN] FROM @Info))
DELETE FROM vg48273.AD_USER_AD_USERGROUP WHERE ADUSER_ID IN (SELECT ADUSER_ID FROM vg48273.AD_USER WHERE ADUSER_DOMAIN IN (SELECT [ADUSER_DOMAIN] FROM @Info))

DELETE FROM vg48273.SCANNER_BATCH WHERE SCANNER_TASK_ID IN (SELECT SCANNER_TASK_ID FROM vg48273.SCANNER_TASK WHERE WORKSTATION_ID IN (SELECT WORK_STATION_ID FROM vg48273.WORK_STATION WHERE WORK_STATION_ADDRESS IN (SELECT WORK_STATION_ADDRESS FROM @Info)))
DELETE  FROM vg48273.AD_USER_DEVICE WHERE ADUSER_ID IN (SELECT ADUSER_ID FROM vg48273.AD_USER WHERE ADUSER_DOMAIN IN (SELECT [ADUSER_DOMAIN] FROM @Info))
DELETE  FROM vg48273.SEARCH_HISTORY WHERE AD_USER_ID IN (SELECT ADUSER_ID FROM vg48273.AD_USER WHERE ADUSER_DOMAIN IN (SELECT [ADUSER_DOMAIN] FROM @Info))
DELETE FROM vg48273.SHOPPINGCART_ITEMS WHERE SHOPPINGCART_ID IN (SELECT SHOPPINGCART_ID FROM vg48273.SHOPPINGCART WHERE CLERK_ID IN (SELECT ADUSER_ID FROM vg48273.AD_USER WHERE ADUSER_DOMAIN IN (SELECT [ADUSER_DOMAIN] FROM @Info)))
DELETE FROM vg48273.SHOPPINGCART WHERE CLERK_ID IN (SELECT ADUSER_ID FROM vg48273.AD_USER WHERE ADUSER_DOMAIN IN (SELECT [ADUSER_DOMAIN] FROM @Info))
DELETE  FROM vg48273.AD_USER WHERE ADUSER_ID IN (SELECT ADUSER_ID FROM vg48273.AD_USER WHERE ADUSER_DOMAIN IN (SELECT [ADUSER_DOMAIN] FROM @Info))

print 'Delete existing workstations'

DELETE FROM vg48273.LOCATION_WORK_STATION WHERE WORK_STATION_ID IN (SELECT WORK_STATION_ID FROM vg48273.WORK_STATION WHERE WORK_STATION_ADDRESS IN (SELECT WORK_STATION_ADDRESS FROM @Info))
DELETE FROM vg48273.WORK_STATION_DEVICE WHERE WORK_STATION_ID IN (SELECT WORK_STATION_ID FROM vg48273.WORK_STATION WHERE WORK_STATION_ADDRESS IN (SELECT WORK_STATION_ADDRESS FROM @Info))
DELETE FROM vg48273.AD_USER_LOGIN_STATISTIC WHERE WORK_STATION_ID IN (SELECT WORK_STATION_ID FROM vg48273.WORK_STATION WHERE WORK_STATION_ADDRESS IN (SELECT WORK_STATION_ADDRESS FROM @Info))
DELETE FROM vg48273.CRS_LOCKED_ELEMENT WHERE WORKSTATION_ID IN (SELECT WORK_STATION_ID FROM vg48273.WORK_STATION WHERE WORK_STATION_ADDRESS IN (SELECT WORK_STATION_ADDRESS FROM @Info))
DELETE FROM vg48273.UPLOAD_IMAGE_ACTIONS_LOG WHERE WORKSTATION_ID IN (SELECT WORK_STATION_ID FROM vg48273.WORK_STATION WHERE WORK_STATION_ADDRESS IN (SELECT WORK_STATION_ADDRESS FROM @Info))

DELETE FROM vg48273.SCANNED_FILE WHERE SCANNER_TASK_ID IN (SELECT SCANNER_TASK_ID FROM vg48273.SCANNER_TASK WHERE WORKSTATION_ID IN (SELECT WORK_STATION_ID FROM vg48273.WORK_STATION WHERE WORK_STATION_ADDRESS IN (SELECT WORK_STATION_ADDRESS FROM @Info)))
DELETE FROM vg48273.SCANNER_TASK WHERE WORKSTATION_ID IN (SELECT WORK_STATION_ID FROM vg48273.WORK_STATION WHERE WORK_STATION_ADDRESS IN (SELECT WORK_STATION_ADDRESS FROM @Info))
DELETE FROM vg48273.SCANNER_WORKSTATION WHERE WORKSTATION_ID IN (SELECT WORK_STATION_ID FROM vg48273.WORK_STATION WHERE WORK_STATION_ADDRESS IN (SELECT WORK_STATION_ADDRESS FROM @Info))
DELETE FROM vg48273.SCANNER_CONFIGURATION_WORKSTATION WHERE WORKSTATION_ID IN (SELECT WORK_STATION_ID FROM vg48273.WORK_STATION WHERE WORK_STATION_ADDRESS IN (SELECT WORK_STATION_ADDRESS FROM @Info))
DELETE FROM vg48273.WORK_STATION WHERE WORK_STATION_ID IN (SELECT WORK_STATION_ID FROM vg48273.WORK_STATION WHERE WORK_STATION_ADDRESS IN (SELECT WORK_STATION_ADDRESS FROM @Info))

print 'Delete existing devices'

DELETE FROM vg48273.DEVICE WHERE DEVICE_HOST_NAME IN (SELECT DEVICE_NAME FROM @Info)

print ''
print 'Start Inserting Users Infos'

print '/*************************** AD_USER AND AD_USERGROUP ****************************************/'
INSERT vg48273.[AD_USER] ([ADUSER_DOMAIN], [ADUSER_USERID], [ADUSER_GROUP], [ADUSER_ENABLED], [ADUSER_FIRSTNAME], [ADUSER_LASTNAME], [ADUSER_MIDDLENAME], [ADUSER_EMAILID], [IS_SUPER_ADMIN], [IS_FIRST_LOGIN], [EXTERNAL_PASSWORD])
SELECT [ADUSER_DOMAIN], N'3bc02b62-309a-4b2a-a9ad-67d60783c871', N'Clerk', 1, [ADUSER_FIRSTNAME], [ADUSER_LASTNAME], NULL, [ADUSER_EMAILID], 0, 0, NULL FROM  @Info 
WHERE [ADUSER_DOMAIN] NOT IN (SELECT [ADUSER_DOMAIN] FROM vg48273.[AD_USER])

INSERT vg48273.[AD_USER_AD_USERGROUP] ( [ADUSER_ID], [AD_USERGROUP_ID], [UG_DEFAULT])
SELECT au.ADUSER_ID, 8, 1 FROM vg48273.[AD_USER] au 
INNER JOIN @Info i ON au.[ADUSER_DOMAIN] = i.[ADUSER_DOMAIN] 
WHERE au.[ADUSER_ENABLED] = 1 AND au.ADUSER_ID NOT IN (SELECT ISNULL(ADUSER_ID, 0) FROM vg48273.[AD_USER_AD_USERGROUP])

print'/*************************** WORK_STATION AND LOCATION ****************************************/'

INSERT vg48273.[WORK_STATION] ( [WORK_STATION_NAME], [WORK_STATION_ADDRESS], [WORK_STATION_DESC], [WS_ENABLED]) 
SELECT [WORK_STATION_NAME], [WORK_STATION_ADDRESS], N'workstation', 1 FROM  @Info WHERE [WORK_STATION_NAME] NOT IN (SELECT [WORK_STATION_NAME] FROM vg48273.[WORK_STATION])

INSERT vg48273.[LOCATION_WORK_STATION] ( LOCATION_ID, [WORK_STATION_ID], [LWS_ENABLED])
SELECT 2, w.[WORK_STATION_ID], 1 FROM vg48273.[WORK_STATION] w 
INNER JOIN @Info i ON w.[WORK_STATION_NAME] = i.[WORK_STATION_NAME] 
WHERE w.[WS_ENABLED] = 1 AND w.WORK_STATION_ID NOT IN (SELECT ISNULL(WORK_STATION_ID, 0) FROM vg48273.[LOCATION_WORK_STATION])

print'/****************************** DEVICE **************************************************************/'
-- DEVICE_SERVICE table
DECLARE @Devices table
(
	[DEVICE_ID] INT,
	[DEVICE_HOST_NAME] nvarchar(250)
);

-- Add new device if table count = 0
if((select Count(Device_service_id) from vg48273.DEVICE_SERVICE) = 0)
BEGIN
	INSERT INTO vg48273.DEVICE_SERVICE 
	VALUES (N'volo', @WorkStationName) 
END

DECLARE @DeviceService INT = 1

INSERT INTO vg48273.[DEVICE]
    ([DEVICE_HOST_NAME],[DEVICE_HOST_ADDR],[DEVICE_DESC],[DEVICE_TYPE_ID],[DEVICE_ACTIVE],[DEVICE_STATUS_ID],[CONFIG_ID],DEVICE_SERVICE_ID)
OUTPUT INSERTED.DEVICE_ID, INSERTED.DEVICE_HOST_NAME INTO @Devices(DEVICE_ID, DEVICE_HOST_NAME)
SELECT [DEVICE_NAME], N'test', 'Drawer', 1,1,1,NULL,@DeviceService FROM @Info 
WHERE [DEVICE_NAME] NOT IN (SELECT DEVICE_HOST_NAME FROM vg48273.[DEVICE] WHERE [DEVICE_TYPE_ID] = 1)

INSERT INTO vg48273.[DEVICE]
    ([DEVICE_HOST_NAME],[DEVICE_HOST_ADDR],[DEVICE_DESC],[DEVICE_TYPE_ID],[DEVICE_ACTIVE],[DEVICE_STATUS_ID],[CONFIG_ID],DEVICE_SERVICE_ID)
OUTPUT INSERTED.DEVICE_ID, INSERTED.DEVICE_HOST_NAME INTO @Devices(DEVICE_ID, DEVICE_HOST_NAME)
SELECT [DEVICE_NAME], [WORK_STATION_ADDRESS], 'Microsoft XPS Document Writer', 2, 1, 1, NULL, @DeviceService FROM @Info 
WHERE [DEVICE_NAME] NOT IN (SELECT DEVICE_HOST_NAME FROM vg48273.[DEVICE] WHERE [DEVICE_TYPE_ID] = 2)

INSERT INTO vg48273.[DEVICE]
    ([DEVICE_HOST_NAME],[DEVICE_HOST_ADDR],[DEVICE_DESC],[DEVICE_TYPE_ID],[DEVICE_ACTIVE],[DEVICE_STATUS_ID],[CONFIG_ID],DEVICE_SERVICE_ID)
OUTPUT INSERTED.DEVICE_ID, INSERTED.DEVICE_HOST_NAME INTO @Devices(DEVICE_ID, DEVICE_HOST_NAME)
SELECT [DEVICE_NAME], N'test', 'Label Printer', 3,1,1,NULL,@DeviceService FROM @Info 
WHERE [DEVICE_NAME] NOT IN (SELECT DEVICE_HOST_NAME FROM vg48273.[DEVICE] WHERE [DEVICE_TYPE_ID] = 3)

INSERT INTO vg48273.[DEVICE]
    ([DEVICE_HOST_NAME],[DEVICE_HOST_ADDR],[DEVICE_DESC],[DEVICE_TYPE_ID],[DEVICE_ACTIVE],[DEVICE_STATUS_ID],[CONFIG_ID],DEVICE_SERVICE_ID)
OUTPUT INSERTED.DEVICE_ID, INSERTED.DEVICE_HOST_NAME INTO @Devices(DEVICE_ID, DEVICE_HOST_NAME)
SELECT [DEVICE_NAME], N'test', 'Receipt Printer', 4,1,1,NULL,@DeviceService FROM @Info 
WHERE [DEVICE_NAME] NOT IN (SELECT DEVICE_HOST_NAME FROM vg48273.[DEVICE] WHERE [DEVICE_TYPE_ID] = 4)

INSERT INTO vg48273.[DEVICE]
    ([DEVICE_HOST_NAME],[DEVICE_HOST_ADDR],[DEVICE_DESC],[DEVICE_TYPE_ID],[DEVICE_ACTIVE],[DEVICE_STATUS_ID],[CONFIG_ID],DEVICE_SERVICE_ID)
OUTPUT INSERTED.DEVICE_ID, INSERTED.DEVICE_HOST_NAME INTO @Devices(DEVICE_ID, DEVICE_HOST_NAME)
SELECT [DEVICE_NAME], N'test', 'Signature Pad', 7,1,1,NULL,@DeviceService FROM @Info 
WHERE [DEVICE_NAME] NOT IN (SELECT DEVICE_HOST_NAME FROM vg48273.[DEVICE] WHERE [DEVICE_TYPE_ID] = 7)

INSERT INTO vg48273.[DEVICE]
    ([DEVICE_HOST_NAME],[DEVICE_HOST_ADDR],[DEVICE_DESC],[DEVICE_TYPE_ID],[DEVICE_ACTIVE],[DEVICE_STATUS_ID],[CONFIG_ID],DEVICE_SERVICE_ID)
OUTPUT INSERTED.DEVICE_ID, INSERTED.DEVICE_HOST_NAME INTO @Devices(DEVICE_ID, DEVICE_HOST_NAME)
SELECT [DEVICE_NAME], N'test', 'Magnetic Card Reader', 8, 1,1,NULL,@DeviceService FROM @Info 
WHERE [DEVICE_NAME] NOT IN (SELECT DEVICE_HOST_NAME FROM vg48273.[DEVICE] WHERE [DEVICE_TYPE_ID] = 8)

INSERT INTO vg48273.[DEVICE]
    ([DEVICE_HOST_NAME],[DEVICE_HOST_ADDR],[DEVICE_DESC],[DEVICE_TYPE_ID],[DEVICE_ACTIVE],[DEVICE_STATUS_ID],[CONFIG_ID],DEVICE_SERVICE_ID)
OUTPUT INSERTED.DEVICE_ID, INSERTED.DEVICE_HOST_NAME INTO @Devices(DEVICE_ID, DEVICE_HOST_NAME)
SELECT [DEVICE_NAME], N'test', 'Slip Printer', 9,1,1,NULL,@DeviceService FROM @Info 
WHERE [DEVICE_NAME] NOT IN (SELECT DEVICE_HOST_NAME FROM vg48273.[DEVICE] WHERE [DEVICE_TYPE_ID] = 1)


INSERT INTO vg48273.[WORK_STATION_DEVICE] ([DEVICE_ID] ,[WORK_STATION_ID],[WSD_ENABLED],[IS_DEFAULT])
SELECT D.DEVICE_ID, w.[WORK_STATION_ID], 1, 1 FROM vg48273.[WORK_STATION] w 
INNER JOIN @Info i ON w.[WORK_STATION_ADDRESS] = i.[WORK_STATION_ADDRESS]
INNER JOIN @Devices AS D ON D.DEVICE_HOST_NAME = I.[DEVICE_NAME]
WHERE D.[DEVICE_ID] NOT IN (SELECT ISNULL(DEVICE_ID, 0) FROM vg48273.[WORK_STATION_DEVICE] WHERE [WORK_STATION_ID] = W.WORK_STATION_ID)

INSERT INTO vg48273.[DEVICE]
    ([DEVICE_HOST_NAME],[DEVICE_HOST_ADDR],[DEVICE_DESC],[DEVICE_TYPE_ID],[DEVICE_ACTIVE],[DEVICE_STATUS_ID],[CONFIG_ID],DEVICE_SERVICE_ID)
OUTPUT INSERTED.DEVICE_ID, INSERTED.DEVICE_HOST_NAME INTO @Devices(DEVICE_ID, DEVICE_HOST_NAME)
SELECT [DEVICE_NAME], N'Agent Drawer', 'Agent Drawer', 1,1,1,NULL,@DeviceService FROM @Info 
WHERE [DEVICE_NAME] NOT IN (SELECT DEVICE_HOST_NAME FROM vg48273.[DEVICE] WHERE [DEVICE_TYPE_ID] = 1 AND [DEVICE_DESC] = 'Agent Drawer')

INSERT INTO vg48273.AD_USER_DEVICE ( DEVICE_ID , ADUSER_ID , WSD_ENABLED , IS_DEFAULT )
SELECT  d.DEVICE_ID, a.ADUSER_ID , 1, 1 FROM vg48273.[AD_USER] a 
INNER JOIN @Info i ON a.ADUSER_DOMAIN = i.ADUSER_DOMAIN
INNER JOIN vg48273.[DEVICE] AS D ON D.[DEVICE_DESC] = 'Agent Drawer' and a.ADUSER_DOMAIN = D.device_host_name

print'/****************************** CRS_SECURITY **************************************************************/'

INSERT INTO vg48273.[CRS_SECURITY_AD_USERGROUP] ([AU_UG_ID],[CRS_SECURABLE_ID],[CRS_SECURITY_AD_USERGROUP_ALLOW_ALL],[CRS_SECURITY_AD_USERGROUP_SECURABLE_PK],[CRS_SECURITY_AD_USERGROUP_ADMIN_ONLY])
SELECT 1, 7, 0, D.DEVICE_ID, 0  FROM @Devices D
INNER JOIN @Info I ON D.DEVICE_HOST_NAME = I.[DEVICE_NAME]
WHERE d.[DEVICE_ID] NOT IN (SELECT ISNULL(CRS_SECURITY_AD_USERGROUP_SECURABLE_PK, 0) FROM vg48273.[CRS_SECURITY_AD_USERGROUP] WHERE AU_UG_ID = 1 AND CRS_SECURABLE_ID = 7)

INSERT INTO vg48273.[CRS_SECURITY_AD_USERGROUP] ([AU_UG_ID],[CRS_SECURABLE_ID],[CRS_SECURITY_AD_USERGROUP_ALLOW_ALL],[CRS_SECURITY_AD_USERGROUP_SECURABLE_PK],[CRS_SECURITY_AD_USERGROUP_ADMIN_ONLY])
SELECT 2, 7, 0, D.DEVICE_ID, 0  FROM @Devices D 
WHERE  d.[DEVICE_ID] NOT IN (SELECT ISNULL(CRS_SECURITY_AD_USERGROUP_SECURABLE_PK, 0) FROM vg48273.[CRS_SECURITY_AD_USERGROUP] WHERE AU_UG_ID = 2 AND CRS_SECURABLE_ID = 7)

INSERT INTO vg48273.[CRS_SECURITY_AD_USERGROUP] ([AU_UG_ID],[CRS_SECURABLE_ID],[CRS_SECURITY_AD_USERGROUP_ALLOW_ALL],[CRS_SECURITY_AD_USERGROUP_SECURABLE_PK],[CRS_SECURITY_AD_USERGROUP_ADMIN_ONLY])
SELECT 3, 7, 0, D.DEVICE_ID, 0  FROM @Devices D
INNER JOIN @Info I ON D.DEVICE_HOST_NAME = I.[DEVICE_NAME]
WHERE d.[DEVICE_ID] NOT IN (SELECT ISNULL(CRS_SECURITY_AD_USERGROUP_SECURABLE_PK, 0) FROM vg48273.[CRS_SECURITY_AD_USERGROUP] WHERE AU_UG_ID = 3 AND CRS_SECURABLE_ID = 7)

INSERT INTO vg48273.[CRS_SECURITY_AD_USERGROUP] ([AU_UG_ID],[CRS_SECURABLE_ID],[CRS_SECURITY_AD_USERGROUP_ALLOW_ALL],[CRS_SECURITY_AD_USERGROUP_SECURABLE_PK],[CRS_SECURITY_AD_USERGROUP_ADMIN_ONLY])
SELECT 4, 7, 0, D.DEVICE_ID, 0  FROM @Devices D
INNER JOIN @Info I ON D.DEVICE_HOST_NAME = I.[DEVICE_NAME]
WHERE d.[DEVICE_ID] NOT IN (SELECT ISNULL(CRS_SECURITY_AD_USERGROUP_SECURABLE_PK, 0) FROM vg48273.[CRS_SECURITY_AD_USERGROUP] WHERE AU_UG_ID = 4 AND CRS_SECURABLE_ID = 7)

INSERT INTO vg48273.[CRS_SECURITY_LOCATION] ([LOCATION_ID],[CRS_SECURABLE_ID],[CRS_SECURITY_LOCATION_ALLOW_ALL],[CRS_SECURITY_LOCATION_SECURABLE_PK],[CRS_SECURITY_LOCATION_ADMIN_ONLY])
SELECT 2, 7, 0, D.DEVICE_ID, 0  FROM @Devices D
INNER JOIN @Info I ON D.DEVICE_HOST_NAME = I.[DEVICE_NAME]
WHERE d.[DEVICE_ID] NOT IN (SELECT ISNULL([CRS_SECURITY_LOCATION_SECURABLE_PK], 0) FROM vg48273.[CRS_SECURITY_LOCATION] WHERE [LOCATION_ID] = 2 AND CRS_SECURABLE_ID = 7)

INSERT INTO vg48273.[CRS_SECURITY_LOCATION] ([LOCATION_ID],[CRS_SECURABLE_ID],[CRS_SECURITY_LOCATION_ALLOW_ALL],[CRS_SECURITY_LOCATION_SECURABLE_PK],[CRS_SECURITY_LOCATION_ADMIN_ONLY])
SELECT 3, 7, 0, D.DEVICE_ID, 0  FROM @Devices D
INNER JOIN @Info I ON D.DEVICE_HOST_NAME = I.[DEVICE_NAME]
WHERE d.[DEVICE_ID] NOT IN (SELECT ISNULL([CRS_SECURITY_LOCATION_SECURABLE_PK], 0) FROM vg48273.[CRS_SECURITY_LOCATION] WHERE [LOCATION_ID] = 3 AND CRS_SECURABLE_ID = 7)

INSERT INTO vg48273.[CRS_SECURITY_WORKSTATION] ([WORK_STATION_ID],[CRS_SECURABLE_ID],[CRS_SECURITY_WORKSTATION_ALLOW_ALL],[CRS_SECURITY_WORKSTATION_SECURABLE_PK],[CRS_SECURITY_WORKSTATION_ADMIN_ONLY])
SELECT  w.WORK_STATION_ID, 7, 0, d.DEVICE_ID, 0 FROM @Devices D
INNER JOIN @Info I ON D.DEVICE_HOST_NAME = I.[DEVICE_NAME]
INNER JOIN vg48273.[WORK_STATION] w ON w.[WORK_STATION_NAME] = i.[WORK_STATION_NAME] 
WHERE d.[DEVICE_ID] NOT IN (SELECT ISNULL([CRS_SECURITY_WORKSTATION_SECURABLE_PK], 0) FROM vg48273.[CRS_SECURITY_WORKSTATION] WHERE WORK_STATION_ID = W.WORK_STATION_ID AND CRS_SECURABLE_ID = 7)


